-- this file is generated by Project X discord.gg/dFqH5jtpqt

local ScreenGui = Instance.new("ScreenGui")

local CanvasGroup = Instance.new("CanvasGroup")

local Frame = Instance.new("Frame")

local Frame2 = Instance.new("Frame")

local TextLabel = Instance.new("TextLabel")

local ImageLabel = Instance.new("ImageLabel")

local ImageButton = Instance.new("ImageButton")

local TextButton = Instance.new("TextButton")

local TextButton2 = Instance.new("TextButton")

local Frame3 = Instance.new("Frame")

local Frame4 = Instance.new("Frame")

local TextBox = Instance.new("TextBox")

local TextButton3 = Instance.new("TextButton")

local TextButton4 = Instance.new("TextButton")

local TextLabel2 = Instance.new("TextLabel")

local Frame5 = Instance.new("Frame")

local UIListLayout = Instance.new("UIListLayout")
local TweenService = game:GetService("TweenService")
local HttpService = game:GetService("HttpService")
local UserInputService = game:GetService("UserInputService")
local RbxAnalyticsService = game:GetService("RbxAnalyticsService")
ScreenGui.Name = "SairoPremium"
ScreenGui.Parent = game.CoreGui
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
CanvasGroup.Name = "Main"
CanvasGroup.Parent = ScreenGui
CanvasGroup.BackgroundColor3 = Color3.fromRGB(12, 12, 12)
CanvasGroup.Position = UDim2.new(0.5, -240, 0.5, -140)
CanvasGroup.Size = UDim2.new(0, 480, 0, 280)
CanvasGroup.BorderSizePixel = 0
CanvasGroup.GroupTransparency = 0

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 14)
UICorner.Parent = CanvasGroup

local UIStroke = Instance.new("UIStroke")
UIStroke.Color = Color3.fromRGB(60, 60, 60)
UIStroke.Thickness = 1
UIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke.Parent = CanvasGroup
ImageButton.Name = "Close"
ImageButton.Parent = ScreenGui
ImageButton.BackgroundTransparency = 1
ImageButton.Position = UDim2.new(0.5, 215, 0.5, -165)
ImageButton.Size = UDim2.new(0, 24, 0, 24)
ImageButton.Image = "rbxassetid://3926305904"
ImageButton.ImageRectOffset = Vector2.new(284, 4)
ImageButton.ImageRectSize = Vector2.new(24, 24)
ImageButton.ImageColor3 = Color3.fromRGB(200, 200, 200)
ImageButton.ZIndex = 10
local connect = ImageButton.MouseEnter:Connect(function(...)
    local tweenInfo = TweenService:Create(ImageButton, TweenInfo.new(0.2), {
        ImageColor3 = Color3.fromRGB(255, 80, 80)
    })
    tweenInfo:Play()
end)

local connect2 = ImageButton.MouseLeave:Connect(function(...)
    local tweenInfo2 = TweenService:Create(ImageButton, TweenInfo.new(0.2), {
        ImageColor3 = Color3.fromRGB(200, 200, 200)
    })
    tweenInfo2:Play()
end)

local connect3 = ImageButton.MouseButton1Click:Connect(function()
    local tweenInfo3 = TweenService:Create(CanvasGroup, TweenInfo.new(0.3), {
        Size = UDim2.new(0, 0, 0, 0),
        GroupTransparency = 1
    })
    tweenInfo3:Play()
    local tweenInfo4 = TweenService:Create(ImageButton, TweenInfo.new(0.3), {
        ImageTransparency = 1
    })
    tweenInfo4:Play()
    wait(0.3)
    ScreenGui:Destroy()
end)

ImageLabel.Name = "Glow"
ImageLabel.Parent = CanvasGroup
ImageLabel.BackgroundTransparency = 1
ImageLabel.Position = UDim2.new(0, -120, 0, -120)
ImageLabel.Size = UDim2.new(1, 240, 1, 240)
ImageLabel.Image = "rbxassetid://5028857472"
ImageLabel.ImageColor3 = Color3.fromRGB(255, 87, 34)
ImageLabel.ImageTransparency = 0.94
ImageLabel.ZIndex = 0
Frame5.Name = "Notifications"
Frame5.Parent = ScreenGui
Frame5.Position = UDim2.new(1, -230, 1, -310)
Frame5.Size = UDim2.new(0, 220, 0, 300)
Frame5.BackgroundTransparency = 1
UIListLayout.Parent = Frame5
UIListLayout.SortOrder = 0
UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Bottom
UIListLayout.Padding = UDim.new(0, 6)
Frame.Name = "Side"
Frame.Parent = CanvasGroup
Frame.BackgroundColor3 = Color3.fromRGB(18, 18, 18)
Frame.Size = UDim2.new(0, 140, 1, 0)
Frame.ZIndex = 2

local UIStroke2 = Instance.new("UIStroke")
UIStroke2.Color = Color3.fromRGB(30, 30, 30)
UIStroke2.Thickness = 1
UIStroke2.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke2.Parent = Frame
UIStroke2.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
TextLabel.Parent = Frame
TextLabel.BackgroundTransparency = 1
TextLabel.Position = UDim2.new(0, 0, 0, 30)
TextLabel.Size = UDim2.new(1, 0, 0, 30)
TextLabel.Font = Enum.Font.GothamBlack
TextLabel.Text = "SAIRO"
TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.TextSize = 24
TextLabel.ZIndex = 2

local UIGradient = Instance.new("UIGradient")
UIGradient.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 87, 34))})
UIGradient.Rotation = 45
UIGradient.Parent = TextLabel

local TextButton5 = Instance.new("TextButton")
TextButton5.Parent = Frame
TextButton5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton5.BackgroundTransparency = 1
TextButton5.Position = UDim2.new(0, 15, 0, 100)
TextButton5.Size = UDim2.new(1, -30, 0, 36)
TextButton5.Font = Enum.Font.GothamMedium
TextButton5.Text = "  Gateway"
TextButton5.TextColor3 = Color3.fromRGB(160, 160, 160)
TextButton5.TextSize = 13
TextButton5.TextXAlignment = Enum.TextXAlignment.Left
TextButton5.ZIndex = 2

local UICorner2 = Instance.new("UICorner")
UICorner2.CornerRadius = UDim.new(0, 8)
UICorner2.Parent = TextButton5

local TextButton6 = Instance.new("TextButton")
TextButton6.Parent = Frame
TextButton6.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextButton6.BackgroundTransparency = 1
TextButton6.Position = UDim2.new(0, 15, 0, 145)
TextButton6.Size = UDim2.new(1, -30, 0, 36)
TextButton6.Font = Enum.Font.GothamMedium
TextButton6.Text = "  Information"
TextButton6.TextColor3 = Color3.fromRGB(160, 160, 160)
TextButton6.TextSize = 13
TextButton6.TextXAlignment = Enum.TextXAlignment.Left
TextButton6.ZIndex = 2

local UICorner3 = Instance.new("UICorner")
UICorner3.CornerRadius = UDim.new(0, 8)
UICorner3.Parent = TextButton6
Frame2.Parent = CanvasGroup
Frame2.BackgroundTransparency = 1
Frame2.Position = UDim2.new(0, 140, 0, 0)
Frame2.Size = UDim2.new(1, -140, 1, 0)
Frame2.ZIndex = 2
Frame3.Parent = Frame2
Frame3.Size = UDim2.new(1, 0, 1, 0)
Frame3.BackgroundTransparency = 1
Frame3.Visible = true
Frame4.Parent = Frame2
Frame4.Size = UDim2.new(1, 0, 1, 0)
Frame4.BackgroundTransparency = 1
Frame4.Visible = false

local TextLabel3 = Instance.new("TextLabel")
TextLabel3.Parent = Frame3
TextLabel3.BackgroundTransparency = 1
TextLabel3.Position = UDim2.new(0, 35, 0, 30)
TextLabel3.Size = UDim2.new(1, -70, 0, 20)
TextLabel3.Font = Enum.Font.GothamBold
TextLabel3.Text = "AUTHENTICATION"
TextLabel3.TextColor3 = Color3.fromRGB(240, 240, 240)
TextLabel3.TextSize = 16
TextLabel3.TextXAlignment = Enum.TextXAlignment.Left

local TextLabel4 = Instance.new("TextLabel")
TextLabel4.Parent = Frame3
TextLabel4.BackgroundTransparency = 1
TextLabel4.Position = UDim2.new(0, 35, 0, 50)
TextLabel4.Size = UDim2.new(1, -70, 0, 30)
TextLabel4.Font = Enum.Font.Gotham
TextLabel4.Text = "A license key is required to access the features of this script."
TextLabel4.TextColor3 = Color3.fromRGB(160, 160, 160)
TextLabel4.TextSize = 12
TextLabel4.TextWrapped = true
TextLabel4.TextXAlignment = Enum.TextXAlignment.Left
TextBox.Parent = Frame3
TextBox.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
TextBox.Position = UDim2.new(0, 35, 0, 100)
TextBox.Size = UDim2.new(1, -70, 0, 48)
TextBox.Font = Enum.Font.Code
TextBox.PlaceholderText = "Paste License Key..."
TextBox.PlaceholderColor3 = Color3.fromRGB(70, 70, 70)
TextBox.Text = ""
TextBox.TextColor3 = Color3.fromRGB(255, 87, 34)
TextBox.TextSize = 14
TextBox.TextXAlignment = Enum.TextXAlignment.Center

local UICorner4 = Instance.new("UICorner")
UICorner4.CornerRadius = UDim.new(0, 10)
UICorner4.Parent = TextBox

local UIStroke3 = Instance.new("UIStroke")
UIStroke3.Color = Color3.fromRGB(45, 45, 45)
UIStroke3.Thickness = 1
UIStroke3.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke3.Parent = TextBox
TextButton4.Parent = Frame3
TextButton4.BackgroundColor3 = Color3.fromRGB(255, 87, 34)
TextButton4.Position = UDim2.new(0, 35, 0, 165)
TextButton4.Size = UDim2.new(0.45, 0, 0, 42)
TextButton4.Font = Enum.Font.GothamBold
TextButton4.Text = "VERIFY KEY"
TextButton4.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton4.TextSize = 12

local UICorner5 = Instance.new("UICorner")
UICorner5.CornerRadius = UDim.new(0, 10)
UICorner5.Parent = TextButton4
TextButton4.AutoButtonColor = false
local connect4 = TextButton4.MouseEnter:Connect(function(...)
    local tweenInfo5 = TweenService:Create(TextButton4, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(255, 112, 67)
    })
    tweenInfo5:Play()
end)

local connect5 = TextButton4.MouseLeave:Connect(function(...)
    local tweenInfo6 = TweenService:Create(TextButton4, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(255, 87, 34)
    })
    tweenInfo6:Play()
end)

local connect6 = TextButton4.MouseButton1Down:Connect(function()
    -- [Error in Connect_Callback] attempt to index a number value (local 't')
end)

local connect7 = TextButton4.MouseButton1Up:Connect(function()
    local tweenInfo7 = TweenService:Create(TextButton4, TweenInfo.new(0.1, Enum.EasingStyle.Bounce), {
        Size = UDim2.new(0.45, 0, 0, 42)
    })
    tweenInfo7:Play()
end)

TextButton3.Parent = Frame3
TextButton3.BackgroundColor3 = Color3.fromRGB(28, 28, 28)
TextButton3.Position = UDim2.new(0.52, 0, 0, 165)
TextButton3.Size = UDim2.new(0.38, 0, 0, 42)
TextButton3.Font = Enum.Font.GothamBold
TextButton3.Text = "GET KEY"
TextButton3.TextColor3 = Color3.fromRGB(220, 220, 220)
TextButton3.TextSize = 12

local UICorner6 = Instance.new("UICorner")
UICorner6.CornerRadius = UDim.new(0, 10)
UICorner6.Parent = TextButton3

local UIStroke4 = Instance.new("UIStroke")
UIStroke4.Color = Color3.fromRGB(45, 45, 45)
UIStroke4.Thickness = 1
UIStroke4.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke4.Parent = TextButton3
local connect8 = TextButton3.MouseEnter:Connect(function(...)
    local tweenInfo8 = TweenService:Create(TextButton3, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(38, 38, 38)
    })
    tweenInfo8:Play()
end)

local connect9 = TextButton3.MouseLeave:Connect(function(...)
    local tweenInfo9 = TweenService:Create(TextButton3, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(28, 28, 28)
    })
    tweenInfo9:Play()
end)

local connect10 = TextButton3.MouseButton1Click:Connect(function()
    local tweenInfo10 = TweenService:Create(TextButton3, TweenInfo.new(0.1), {
        Size = UDim2.new(0.361, 0, 0, 39.9)
    })
    tweenInfo10:Play()
    wait(0.1)
    local tweenInfo11 = TweenService:Create(TextButton3, TweenInfo.new(0.1), {
        Size = UDim2.new(0.38, 0, 0, 42)
    })
    tweenInfo11:Play()
end)

TextLabel2.Parent = Frame3
TextLabel2.BackgroundTransparency = 1
TextLabel2.Position = UDim2.new(0, 35, 1, -35)
TextLabel2.Size = UDim2.new(1, -70, 0, 20)
TextLabel2.Font = Enum.Font.GothamBold
TextLabel2.Text = "WAITING FOR INPUT"
TextLabel2.TextColor3 = Color3.fromRGB(80, 80, 80)
TextLabel2.TextSize = 10
TextLabel2.TextXAlignment = Enum.TextXAlignment.Center

local ScrollingFrame = Instance.new("ScrollingFrame")
ScrollingFrame.Parent = Frame4
ScrollingFrame.BackgroundTransparency = 1
ScrollingFrame.Position = UDim2.new(0, 20, 0, 20)
ScrollingFrame.Size = UDim2.new(1, -40, 1, -40)
ScrollingFrame.ScrollBarThickness = 2
ScrollingFrame.BorderSizePixel = 0

local TextLabel5 = Instance.new("TextLabel")
TextLabel5.Parent = ScrollingFrame
TextLabel5.BackgroundTransparency = 1
TextLabel5.Size = UDim2.new(1, 0, 0, 30)
TextLabel5.Font = Enum.Font.GothamBold
TextLabel5.Text = "INFORMATION"
TextLabel5.TextColor3 = Color3.fromRGB(240, 240, 240)
TextLabel5.TextSize = 16
TextLabel5.TextXAlignment = Enum.TextXAlignment.Left

local UIListLayout2 = Instance.new("UIListLayout")
UIListLayout2.Parent = ScrollingFrame
UIListLayout2.SortOrder = 0
UIListLayout2.Padding = UDim.new(0, 10)

local TextButton7 = Instance.new("TextButton")
TextButton7.Parent = ScrollingFrame
TextButton7.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
TextButton7.Size = UDim2.new(1, 0, 0, 60)
TextButton7.AutoButtonColor = false
TextButton7.Text = ""

local UICorner7 = Instance.new("UICorner")
UICorner7.CornerRadius = UDim.new(0, 10)
UICorner7.Parent = TextButton7

local UIStroke5 = Instance.new("UIStroke")
UIStroke5.Color = Color3.fromRGB(45, 45, 45)
UIStroke5.Thickness = 1
UIStroke5.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke5.Parent = TextButton7

local TextLabel6 = Instance.new("TextLabel")
TextLabel6.Parent = TextButton7
TextLabel6.BackgroundTransparency = 1
TextLabel6.Position = UDim2.new(0, 15, 0, 12)
TextLabel6.Size = UDim2.new(1, -30, 0, 20)
TextLabel6.Font = Enum.Font.GothamBold
TextLabel6.Text = "Discord Server"
TextLabel6.TextColor3 = Color3.fromRGB(240, 240, 240)
TextLabel6.TextSize = 14
TextLabel6.TextXAlignment = Enum.TextXAlignment.Left

local TextLabel7 = Instance.new("TextLabel")
TextLabel7.Parent = TextButton7
TextLabel7.BackgroundTransparency = 1
TextLabel7.Position = UDim2.new(0, 15, 0, 32)
TextLabel7.Size = UDim2.new(1, -30, 0, 15)
TextLabel7.Font = Enum.Font.Gotham
TextLabel7.Text = "Join our community for support."
TextLabel7.TextColor3 = Color3.fromRGB(160, 160, 160)
TextLabel7.TextSize = 11
TextLabel7.TextXAlignment = Enum.TextXAlignment.Left

local ImageLabel2 = Instance.new("ImageLabel")
ImageLabel2.Parent = TextButton7
ImageLabel2.BackgroundTransparency = 1
ImageLabel2.Position = UDim2.new(1, -40, 0.5, -10)
ImageLabel2.Size = UDim2.new(0, 20, 0, 20)
ImageLabel2.Image = "rbxassetid://16123490977"
ImageLabel2.ImageColor3 = Color3.fromRGB(255, 87, 34)
local connect11 = TextButton7.MouseEnter:Connect(function(...)
    local tweenInfo12 = TweenService:Create(TextButton7, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    })
    tweenInfo12:Play()
end)

local connect12 = TextButton7.MouseLeave:Connect(function(...)
    local tweenInfo13 = TweenService:Create(TextButton7, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(22, 22, 22)
    })
    tweenInfo13:Play()
end)

local connect13 = TextButton7.MouseButton1Click:Connect(function()
    setclipboard("https://discord.gg/yourinvite")
    
    local Frame6 = Instance.new("Frame")
    Frame6.Name = "Notif"
    Frame6.Parent = Frame5
    Frame6.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    Frame6.BorderSizePixel = 0
    Frame6.Size = UDim2.new(1, 0, 0, 50)
    Frame6.BackgroundTransparency = 1
    
    local UICorner8 = Instance.new("UICorner")
    UICorner8.CornerRadius = UDim.new(0, 6)
    UICorner8.Parent = Frame6
    
    local UIStroke6 = Instance.new("UIStroke")
    UIStroke6.Color = Color3.fromRGB(45, 45, 45)
    UIStroke6.Thickness = 1
    UIStroke6.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    UIStroke6.Parent = Frame6
    
    local TextLabel8 = Instance.new("TextLabel")
    TextLabel8.Parent = Frame6
    TextLabel8.BackgroundTransparency = 1
    TextLabel8.Position = UDim2.new(0, 10, 0, 5)
    TextLabel8.Size = UDim2.new(1, -20, 0, 20)
    TextLabel8.Font = Enum.Font.GothamBold
    TextLabel8.Text = "Discord"
    TextLabel8.TextColor3 = Color3.fromRGB(255, 87, 34)
    TextLabel8.TextSize = 13
    TextLabel8.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel8.TextTransparency = 1
    
    local TextLabel9 = Instance.new("TextLabel")
    TextLabel9.Parent = Frame6
    TextLabel9.BackgroundTransparency = 1
    TextLabel9.Position = UDim2.new(0, 10, 0, 22)
    TextLabel9.Size = UDim2.new(1, -20, 0, 20)
    TextLabel9.Font = Enum.Font.Gotham
    TextLabel9.Text = "Invite copied to clipboard."
    TextLabel9.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextLabel9.TextSize = 12
    TextLabel9.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel9.TextTransparency = 1
    local tweenInfo14 = TweenService:Create(Frame6, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.05
    })
    tweenInfo14:Play()
    local tweenInfo15 = TweenService:Create(TextLabel8, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo15:Play()
    local tweenInfo16 = TweenService:Create(TextLabel9, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo16:Play()
    task.delay(3, function()
        local tweenInfo17 = TweenService:Create(Frame6, TweenInfo.new(0.3), {
            BackgroundTransparency = 1
        })
        tweenInfo17:Play()
        local tweenInfo18 = TweenService:Create(TextLabel8, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo18:Play()
        local tweenInfo19 = TweenService:Create(TextLabel9, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo19:Play()
        local tweenInfo20 = TweenService:Create(UIStroke6, TweenInfo.new(0.3), {
            Transparency = 1
        })
        tweenInfo20:Play()
        wait(0.3)
        Frame6:Destroy()
    end)
end)


local TextButton8 = Instance.new("TextButton")
TextButton8.Parent = ScrollingFrame
TextButton8.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
TextButton8.Size = UDim2.new(1, 0, 0, 60)
TextButton8.AutoButtonColor = false
TextButton8.Text = ""

local UICorner9 = Instance.new("UICorner")
UICorner9.CornerRadius = UDim.new(0, 10)
UICorner9.Parent = TextButton8

local UIStroke7 = Instance.new("UIStroke")
UIStroke7.Color = Color3.fromRGB(45, 45, 45)
UIStroke7.Thickness = 1
UIStroke7.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
UIStroke7.Parent = TextButton8

local TextLabel10 = Instance.new("TextLabel")
TextLabel10.Parent = TextButton8
TextLabel10.BackgroundTransparency = 1
-- [Infinite loop/spam detected... suppression active. Continuing main execution...]
TextLabel10.Text = "Website"
TextLabel10.TextColor3 = Color3.fromRGB(240, 240, 240)
TextLabel10.TextSize = 14
TextLabel10.TextXAlignment = Enum.TextXAlignment.Left

local TextLabel11 = Instance.new("TextLabel")
TextLabel11.Parent = TextButton8
TextLabel11.BackgroundTransparency = 1
TextLabel11.Position = UDim2.new(0, 15, 0, 32)
TextLabel11.Size = UDim2.new(1, -30, 0, 15)
TextLabel11.Font = Enum.Font.Gotham
TextLabel11.Text = "Visit the official site."
TextLabel11.TextColor3 = Color3.fromRGB(160, 160, 160)
TextLabel11.TextSize = 11
TextLabel11.TextXAlignment = Enum.TextXAlignment.Left

local ImageLabel3 = Instance.new("ImageLabel")
ImageLabel3.Parent = TextButton8
ImageLabel3.BackgroundTransparency = 1
ImageLabel3.Position = UDim2.new(1, -40, 0.5, -10)
ImageLabel3.Size = UDim2.new(0, 20, 0, 20)
ImageLabel3.Image = "rbxassetid://16123492577"
ImageLabel3.ImageColor3 = Color3.fromRGB(255, 87, 34)
local connect14 = TextButton8.MouseEnter:Connect(function(...)
    local tweenInfo21 = TweenService:Create(TextButton8, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    })
    tweenInfo21:Play()
end)

local connect15 = TextButton8.MouseLeave:Connect(function(...)
    local tweenInfo22 = TweenService:Create(TextButton8, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(22, 22, 22)
    })
    tweenInfo22:Play()
end)

-- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    setclipboard("https://yourwebsite.com")
    
    local Frame7 = Instance.new("Frame")
    Frame7.Name = "Notif"
    Frame7.Parent = Frame5
    Frame7.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    Frame7.BorderSizePixel = 0
    Frame7.Size = UDim2.new(1, 0, 0, 50)
    Frame7.BackgroundTransparency = 1
    
    local UICorner10 = Instance.new("UICorner")
    UICorner10.CornerRadius = UDim.new(0, 6)
    UICorner10.Parent = Frame7
    
    local UIStroke8 = Instance.new("UIStroke")
    UIStroke8.Color = Color3.fromRGB(45, 45, 45)
    UIStroke8.Thickness = 1
    UIStroke8.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    UIStroke8.Parent = Frame7
    
    local TextLabel12 = Instance.new("TextLabel")
    TextLabel12.Parent = Frame7
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    TextLabel12.Text = "Website"
    TextLabel12.TextColor3 = Color3.fromRGB(255, 87, 34)
    TextLabel12.TextSize = 13
    TextLabel12.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel12.TextTransparency = 1
    
    local TextLabel13 = Instance.new("TextLabel")
    TextLabel13.Parent = Frame7
    TextLabel13.BackgroundTransparency = 1
    TextLabel13.Position = UDim2.new(0, 10, 0, 22)
    TextLabel13.Size = UDim2.new(1, -20, 0, 20)
    TextLabel13.Font = Enum.Font.Gotham
    TextLabel13.Text = "Link copied to clipboard."
    TextLabel13.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextLabel13.TextSize = 12
    TextLabel13.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel13.TextTransparency = 1
    local tweenInfo23 = TweenService:Create(Frame7, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.05
    })
    tweenInfo23:Play()
    local tweenInfo24 = TweenService:Create(TextLabel12, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo24:Play()
    local tweenInfo25 = TweenService:Create(TextLabel13, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo25:Play()
    task.delay(3, function()
        local tweenInfo26 = TweenService:Create(Frame7, TweenInfo.new(0.3), {
            BackgroundTransparency = 1
        })
        tweenInfo26:Play()
        local tweenInfo27 = TweenService:Create(TextLabel12, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo27:Play()
        local tweenInfo28 = TweenService:Create(TextLabel13, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo28:Play()
        local tweenInfo29 = TweenService:Create(UIStroke8, TweenInfo.new(0.3), {
            Transparency = 1
        })
        tweenInfo29:Play()
        wait(0.3)
        Frame7:Destroy()
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
v110.Text = "Credits"
v110.TextColor3 = Color3.fromRGB(240, 240, 240)
v110.TextSize = 14
v110.TextXAlignment = Enum.TextXAlignment.Left

local TextLabel14 = Instance.new("TextLabel")
TextLabel14.Parent = v107
TextLabel14.BackgroundTransparency = 1
TextLabel14.Position = UDim2.new(0, 15, 0, 32)
TextLabel14.Size = UDim2.new(1, -30, 0, 15)
TextLabel14.Font = Enum.Font.Gotham
TextLabel14.Text = "Developed by Sairo Team."
TextLabel14.TextColor3 = Color3.fromRGB(160, 160, 160)
TextLabel14.TextSize = 11
TextLabel14.TextXAlignment = Enum.TextXAlignment.Left

local ImageLabel4 = Instance.new("ImageLabel")
ImageLabel4.Parent = v107
ImageLabel4.BackgroundTransparency = 1
ImageLabel4.Position = UDim2.new(1, -40, 0.5, -10)
ImageLabel4.Size = UDim2.new(0, 20, 0, 20)
ImageLabel4.Image = "rbxassetid://16123492213"
ImageLabel4.ImageColor3 = Color3.fromRGB(255, 87, 34)
local connect16 = v107.MouseEnter:Connect(function(...)
    local tweenInfo30 = TweenService:Create(v107, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    })
    tweenInfo30:Play()
end)

local connect17 = v107.MouseLeave:Connect(function(...)
    local tweenInfo31 = TweenService:Create(v107, TweenInfo.new(0.2), {
        BackgroundColor3 = Color3.fromRGB(22, 22, 22)
    })
    tweenInfo31:Play()
end)

-- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    
    local Frame8 = Instance.new("Frame")
    Frame8.Name = "Notif"
    Frame8.Parent = Frame5
    Frame8.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    Frame8.BorderSizePixel = 0
    Frame8.Size = UDim2.new(1, 0, 0, 50)
    Frame8.BackgroundTransparency = 1
    
    local UICorner11 = Instance.new("UICorner")
    UICorner11.CornerRadius = UDim.new(0, 6)
    UICorner11.Parent = Frame8
    
    local UIStroke9 = Instance.new("UIStroke")
    UIStroke9.Color = Color3.fromRGB(45, 45, 45)
    UIStroke9.Thickness = 1
    UIStroke9.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    UIStroke9.Parent = Frame8
    
    local TextLabel15 = Instance.new("TextLabel")
    TextLabel15.Parent = Frame8
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    TextLabel15.Text = "Credits"
    TextLabel15.TextColor3 = Color3.fromRGB(255, 87, 34)
    TextLabel15.TextSize = 13
    TextLabel15.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel15.TextTransparency = 1
    
    local TextLabel16 = Instance.new("TextLabel")
    TextLabel16.Parent = Frame8
    TextLabel16.BackgroundTransparency = 1
    TextLabel16.Position = UDim2.new(0, 10, 0, 22)
    TextLabel16.Size = UDim2.new(1, -20, 0, 20)
    TextLabel16.Font = Enum.Font.Gotham
    TextLabel16.Text = "Script by Sairo Devs"
    TextLabel16.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextLabel16.TextSize = 12
    TextLabel16.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel16.TextTransparency = 1
    local tweenInfo32 = TweenService:Create(Frame8, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.05
    })
    tweenInfo32:Play()
    local tweenInfo33 = TweenService:Create(TextLabel15, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo33:Play()
    local tweenInfo34 = TweenService:Create(TextLabel16, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo34:Play()
    task.delay(3, function()
        local tweenInfo35 = TweenService:Create(Frame8, TweenInfo.new(0.3), {
            BackgroundTransparency = 1
        })
        tweenInfo35:Play()
        local tweenInfo36 = TweenService:Create(TextLabel15, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo36:Play()
        local tweenInfo37 = TweenService:Create(TextLabel16, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo37:Play()
        local tweenInfo38 = TweenService:Create(UIStroke9, TweenInfo.new(0.3), {
            Transparency = 1
        })
        tweenInfo38:Play()
        wait(0.3)
        Frame8:Destroy()
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
local connect18 = TextButton3.MouseButton1Click:Connect(function()
    TextLabel2.Text = "CONTACTING SERVER..."
    TextLabel2.TextColor3 = Color3.fromRGB(240, 240, 240)
    local requestResult = request({
        Body = HttpService:JSONEncode({
        hwid = "DE2GTA25-3FVW-AAWA-D522-000000000000"
    }),
        Method = "POST",
        Url = "https://webservice-g7b9.onrender.com/api/init",
        Headers = {
            ["Content-Type"] = "application/json"
        }
    })
    TextLabel2.Text = "CONNECTION FAILED"
    TextLabel2.TextColor3 = Color3.fromRGB(255, 80, 80)
    
    local Frame9 = Instance.new("Frame")
    Frame9.Name = "Notif"
    Frame9.Parent = Frame5
    Frame9.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    Frame9.BorderSizePixel = 0
    Frame9.Size = UDim2.new(1, 0, 0, 50)
    Frame9.BackgroundTransparency = 1
    
    local UICorner12 = Instance.new("UICorner")
    UICorner12.CornerRadius = UDim.new(0, 6)
    UICorner12.Parent = Frame9
    
    local UIStroke10 = Instance.new("UIStroke")
    UIStroke10.Color = Color3.fromRGB(45, 45, 45)
    UIStroke10.Thickness = 1
    UIStroke10.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    UIStroke10.Parent = Frame9
    
    local TextLabel17 = Instance.new("TextLabel")
    TextLabel17.Parent = Frame9
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    TextLabel17.Text = "Connection Error"
    TextLabel17.TextColor3 = Color3.fromRGB(255, 87, 34)
    TextLabel17.TextSize = 13
    TextLabel17.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel17.TextTransparency = 1
    
    local TextLabel18 = Instance.new("TextLabel")
    TextLabel18.Parent = Frame9
    TextLabel18.BackgroundTransparency = 1
    TextLabel18.Position = UDim2.new(0, 10, 0, 22)
    TextLabel18.Size = UDim2.new(1, -20, 0, 20)
    TextLabel18.Font = Enum.Font.Gotham
    TextLabel18.Text = "Could not reach server."
    TextLabel18.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextLabel18.TextSize = 12
    TextLabel18.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel18.TextTransparency = 1
    local tweenInfo39 = TweenService:Create(Frame9, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.05
    })
    tweenInfo39:Play()
    local tweenInfo40 = TweenService:Create(TextLabel17, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo40:Play()
    local tweenInfo41 = TweenService:Create(TextLabel18, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo41:Play()
    task.delay(4, function()
        local tweenInfo42 = TweenService:Create(Frame9, TweenInfo.new(0.3), {
            BackgroundTransparency = 1
        })
        tweenInfo42:Play()
        local tweenInfo43 = TweenService:Create(TextLabel17, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo43:Play()
        local tweenInfo44 = TweenService:Create(TextLabel18, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo44:Play()
        local tweenInfo45 = TweenService:Create(UIStroke10, TweenInfo.new(0.3), {
            Transparency = 1
        })
        tweenInfo45:Play()
        wait(0.3)
        Frame9:Destroy()
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    
    local Frame10 = Instance.new("Frame")
    Frame10.Name = "Notif"
    Frame10.Parent = Frame5
    Frame10.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    Frame10.BorderSizePixel = 0
    Frame10.Size = UDim2.new(1, 0, 0, 50)
    Frame10.BackgroundTransparency = 1
    
    local UICorner13 = Instance.new("UICorner")
    UICorner13.CornerRadius = UDim.new(0, 6)
    UICorner13.Parent = Frame10
    
    local UIStroke11 = Instance.new("UIStroke")
    UIStroke11.Color = Color3.fromRGB(45, 45, 45)
    UIStroke11.Thickness = 1
    UIStroke11.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    UIStroke11.Parent = Frame10
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    v148.Text = "Input Required"
    v148.TextColor3 = Color3.fromRGB(255, 87, 34)
    v148.TextSize = 13
    v148.TextXAlignment = Enum.TextXAlignment.Left
    v148.TextTransparency = 1
    
    local TextLabel19 = Instance.new("TextLabel")
    TextLabel19.Parent = Frame10
    TextLabel19.BackgroundTransparency = 1
    TextLabel19.Position = UDim2.new(0, 10, 0, 22)
    TextLabel19.Size = UDim2.new(1, -20, 0, 20)
    TextLabel19.Font = Enum.Font.Gotham
    TextLabel19.Text = "Please paste your key."
    TextLabel19.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextLabel19.TextSize = 12
    TextLabel19.TextXAlignment = Enum.TextXAlignment.Left
    TextLabel19.TextTransparency = 1
    local tweenInfo46 = TweenService:Create(Frame10, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.05
    })
    tweenInfo46:Play()
    local tweenInfo47 = TweenService:Create(v148, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo47:Play()
    local tweenInfo48 = TweenService:Create(TextLabel19, TweenInfo.new(0.3), {
        TextTransparency = 0
    })
    tweenInfo48:Play()
    task.delay(3, function()
        local tweenInfo49 = TweenService:Create(Frame10, TweenInfo.new(0.3), {
            BackgroundTransparency = 1
        })
        tweenInfo49:Play()
        local tweenInfo50 = TweenService:Create(v148, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo50:Play()
        local tweenInfo51 = TweenService:Create(TextLabel19, TweenInfo.new(0.3), {
            TextTransparency = 1
        })
        tweenInfo51:Play()
        local tweenInfo52 = TweenService:Create(UIStroke11, TweenInfo.new(0.3), {
            Transparency = 1
        })
        tweenInfo52:Play()
        wait(0.3)
        Frame10:Destroy()
    -- [Infinite loop/spam detected... suppression active. Continuing main execution...]
    Frame3.Visible = false
    Frame4.Visible = false
    Frame3.Visible = true
    TextButton5.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextButton6.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextButton5.BackgroundTransparency = 1
    TextButton6.BackgroundTransparency = 1
    TextButton5.TextColor3 = Color3.fromRGB(240, 240, 240)
    local tweenInfo53 = TweenService:Create(TextButton5, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.92
    })
    tweenInfo53:Play()
end)

local connect19 = TextButton6.MouseButton1Click:Connect(function()
    Frame3.Visible = false
    Frame4.Visible = false
    Frame4.Visible = true
    TextButton5.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextButton6.TextColor3 = Color3.fromRGB(160, 160, 160)
    TextButton5.BackgroundTransparency = 1
    TextButton6.BackgroundTransparency = 1
    TextButton6.TextColor3 = Color3.fromRGB(240, 240, 240)
    local tweenInfo54 = TweenService:Create(TextButton6, TweenInfo.new(0.3), {
        BackgroundTransparency = 0.92
    })
    tweenInfo54:Play()
end)

local connect20 = CanvasGroup.InputBegan:Connect(function(input, gameProcessed)
end)

local connect21 = CanvasGroup.InputChanged:Connect(function(input, gameProcessed)
end)

local connect22 = UserInputService.InputChanged:Connect(function(input, gameProcessed)
end)

Frame3.Visible = false
Frame4.Visible = false
Frame3.Visible = true
TextButton5.TextColor3 = Color3.fromRGB(160, 160, 160)
TextButton6.TextColor3 = Color3.fromRGB(160, 160, 160)
TextButton5.BackgroundTransparency = 1
TextButton6.BackgroundTransparency = 1
TextButton5.TextColor3 = Color3.fromRGB(240, 240, 240)
local tweenInfo55 = TweenService:Create(TextButton5, TweenInfo.new(0.3), {
    BackgroundTransparency = 0.92
})
tweenInfo55:Play()
-- Script terminated: attempt to index a number value (local 'qp')